name: Package Generator

on: push

jobs:
  private:
    runs-on: ubuntu-latest
    container:
      image: europe-southwest1-docker.pkg.dev/robotnik-5830-dev/ci-cd-experimental/package_builder:melodic
      credentials:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: 'catkin_ws/src/'

    - name: Download dependencies
      run: |
        . /opt/ros/melodic/setup.sh
        sudo apt-get update
        sudo rosdep init
        rosdep update
        rosdep install --from-paths catkin_ws/src --ignore-src -r -y

    - name: Compile
      run: |
        . /opt/ros/melodic/setup.sh
        cd catkin_ws/
        catkin build

    - name: Generate DEB
      run: |
        . /opt/ros/melodic/setup.sh
        cd catkin_ws/
        generate_debs

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: debs
        path: catkin_ws/debs/
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: catkin_ws/debs/*

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.PUB_CREDENTIALS }}'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0.10.2'
      with:
        path: 'catkin_ws/debs'
        destination: 'sonic-progress-363210/europe-southwest1/quickstart-apt-repo' 

    