name: Package Generator

on: push

jobs:
  build:
    image: europe-southwest1-docker.pkg.dev/robotnik-5830-dev/ci-cd-experimental/package_builder:melodic
    credentials:
      username: ${{ secrets.GH_PASSWORD }}
      password: ${{ secrets.GH_USERNAME }}

    